name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git cmake libasound2-dev libx11-dev \
            libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev \
            libxinerama-dev libwayland-dev libxkbcommon-dev
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install
          cd ../../

      - name: Compile nob
        run: gcc -o nob nob.c

      - name: Build project (Linux)
        run: ./nob

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-linux
          path: phasmocrono

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install MinGW-w64
        run: choco install w64devkit -y

      - name: Download Raylib precompiled
        run: |
          curl -L -o raylib.zip https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_mingw-w64.zip
          tar -xf raylib.zip

      - name: Compile nob
        run: gcc -o nob nob.c
        shell: bash

      - name: Build project (Windows)
        run: ./nob
        shell: bash

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-windows
          path: phasmocrono.exe
