name: Build Phasmocrono

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libraylib-dev

      - name: Build (Linux)
        run: |
          gcc nob.c -o nob
          ./nob

      - uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-linux
          path: phasmocrono

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Download Raylib (Windows)
        run: |
          wget https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_mingw.zip
          unzip raylib-5.5_win64_mingw.zip -d raylib_win

      - name: Build (Windows cross)
        run: |
          gcc nob.c -o nob
          ./nob --win

      - uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-windows
          path: phasmocrono.exe
