name: Build Project - Windows (Debug Raylib Path)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows-debug:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Descargar y descomprimir Raylib
      - name: Download and Extract Raylib
        run: |
          curl -L -o raylib.zip https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_mingw-w64.zip
          Expand-Archive raylib.zip

      # Imprimir contenido de la carpeta para verificar paths
      - name: List Raylib folder
        run: dir raylib-5.5_win64_mingw-w64 /s

      # Compilar nob
      - name: Compile nob
        run: gcc -o nob nob.c
        shell: bash

      # Compilar tu proyecto
      - name: Build project
        run: ./nob
        shell: bash

      # Subir el exe como artifact
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-windows
          path: phasmocrono.exe
