name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git cmake libasound2-dev libx11-dev \
            libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev \
            libxinerama-dev libwayland-dev libxkbcommon-dev
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install
          cd ../../

      - name: Compile nob
        run: gcc -o nob nob.c

      - name: Build project (Linux)
        run: ./nob

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-linux
          path: phasmocrono

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and Install W64Devkit
        run: |
          powershell -Command "Invoke-WebRequest -Uri 'https://github.com/skeeto/w64devkit/releases/download/v2.4.0/w64devkit-x86-2.4.0.7z.exe' -OutFile 'w64devkit.exe'"
          start /wait "" w64devkit.exe /S /D=%CD%\w64devkit
          setx PATH "%PATH%;%CD%\w64devkit"
      
      - name: Download Raylib
        run: |
          curl -L -o raylib.zip https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_mingw-w64.zip
          tar -xf raylib.zip

      # Compilar nob
      - name: Compile nob
        run: gcc -o nob nob.c
        shell: bash

      # Compilar tu proyecto usando nob
      - name: Build Project
        run: ./nob
        shell: bash

      # Subir binario como artifact
      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: phasmocrono-windows
          path: phasmocrono.exe
